//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int Id_Estudiantes { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string FechaNacimiento { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<int> Matricula { get; set; }
        public Nullable<int> Nacionalidad_id { get; set; }
        public string Carrera { get; set; }
        public string FechaInicio { get; set; }
        public string FechaFinalizacion { get; set; }
        public bool IsActive { get; set; }
    }
}
